delta_journal:
  path: /delta/journal
  methods: GET
  defaults: { _controller: Evrinoma\Delta8Bundle\Controller\Delta8Controller::deltaJournal}
  options:
    expose: true

delta_rtt:
  path: /delta/rtt
  methods: GET
  defaults: { _controller: Evrinoma\Delta8Bundle\Controller\Delta8Controller::deltaJournalRtt}
  options:
    expose: true

delta_tree:
  path: /delta/tree
  methods: GET
  defaults: { _controller: Evrinoma\Delta8Bundle\Controller\Delta8Controller::deltaJournalTree}
  options:
    expose: true