services:
  evrinoma.delta8.controller:
    class: Evrinoma\Delta8Bundle\Controller\Delta8Controller
    autowire: true

  Evrinoma\Delta8Bundle\Controller\Delta8Controller:
    alias: evrinoma.delta8.controller
    public: true

  evrinoma.delta8.api.controller:
    class: Evrinoma\Delta8Bundle\Controller\Delta8ApiController
    arguments:
      - '@jms_serializer'
      - '@request_stack'
      - '@evrinoma.delta8.journal.manager'
    autowire: true

  Evrinoma\Delta8Bundle\Controller\Delta8ApiController:
    alias: evrinoma.delta8.api.controller
    public: true

  evrinoma.delta8.journal.manager:
    class: Evrinoma\Delta8Bundle\Manager\JournalManager
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@doctrine'
      - '@evrinoma.settings.manager'

  Evrinoma\Delta8Bundle\Manager\JournalManager:
    alias: evrinoma.delta8.journal.manager
    public: true

  evrinoma.delta8.object_manager:
    class: Doctrine\Persistence\ObjectManager

  evrinoma.delta8.form.rest.dataflow:
    class: Evrinoma\Delta8Bundle\Form\Rest\DataFlowType
    arguments:
      - '@evrinoma.delta8.journal.manager'
    tags: { - name: form.type }
